export const SALT_ROUNDS = 11;

export const JWT_CONSTANTS = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN,

  ADMIN_ACCESS_TOKEN_SECRET: process.env.ADMIN_ACCESS_TOKEN_SECRET,
  ADMIN_ACCESS_TOKEN_EXPIRES_IN: process.env.ADMIN_ACCESS_TOKEN_EXPIRES_IN,
  ADMIN_REFRESH_TOKEN_SECRET: process.env.ADMIN_REFRESH_TOKEN_SECRET,
  ADMIN_REFRESH_TOKEN_EXPIRES_IN: process.env.ADMIN_REFRESH_TOKEN_EXPIRES_IN,
};
