export const ROOM_IDS = [
  // 'Craps00000000001',
  // 'PowerInfiniteBJ1',
  'mrfykemt5slanyi5',
  'SpeedBlackjack03',
  'ps3ufteekfe2fu24',
  'ps3uijuskfe2f3cj',
  'p2f2zs26tc2mu7r5',
  'SpeedBlackjack14',
  'SpeedBlackjack15',
  'SpeedBlackjack16',
  'SpeedBlackjack17',
  'SpeedBlackjack18',
  // 'CFreeBetBjVIP002', // Free bet
  'nveq65dtmn6n4mnd',
  'nveq66tfmn6n4moi',
  'bciewncrf5ijneys',
  '2uxabtm1rwaxcmdm',
  'o735cjzyaeasv4o6',
  'o735di2eiwssv7eu',
  'o735efxfaeasv666',
  'o735fhvsaeaswamh',
  'pdk5xfrkjkgepmlq',
  'pdk5yexcz4iepelq',
  'pdk5yzyfjkgepoml',
  'pdk52e3rey6upyie',
  'pdk523jney6upzft',
  'ps3t7nhskfe2fhkj',
  'p2fzwauitc2msrik',
  'p2f2lphftc2muaql',
  // 'p5s3chh6m7wenyxl',
  'qfyw6u63rixe3foz',
  'qfyxgwwsrcfe5lq3',
  'q6wo6fjprnlhuf36',
  'q6wo7mqrrnlhuj6b',
  'rctfyut2btsmfyyt',
  'rctf4gu6btsmghbt',
  'oqicznoauwbl46am',
  'oqic5sqbt25322zm',
  'oqidcfpsuwbl5cqd',
  'qlrc3fq3v7p6awm4',
  'qckwjf2o52r9ikeb',
  'gazgtkid9h1b0dn9',
  '0mvn914lkmo9vaq8',
  'cpxl81x0rgi34cmo',
  'o3d9tx3u8kd0yawc',
  'psm2um7k4da8zwc2',
  'm6mfo66sb7eafnzz',
  'm6mfsirtb7eafn5c',
  'nbjettfehawanhes',
  'oa7fvyaiqfueq5ob',
  'bghflgi59db7d7r2',
  'o735ggd5iwsswcz7',
  'o735hfcqauecwjxp',
  'pdk53n4bjkgepr5u',
  'lnofoyxv756qaezy',
  'lnofpmm3756qae2c',
  'l5aug44hhzr3qvxs',
  'z5pf5pichcsw3d2o',
  's63nx2mpdomgjagb',
  'lnofn2yl756qaezm',
  'h463tlq1rhl1lfr2',
  'ejx1a04w4ben0mou',
  'nbjetztthawanhey',
  'nsxqpyiol2nzcz6t',
  'gfzrqe4hqv24kukc',
  'rdefcn4sffgo39l7',
  // 'olbibp3fylzaxvhb', // Salon Private
  // 'mdkqfe74dctrhntj', // Salon Private
  // 'SalPrivBJ0000005', // Salon Private
  // 'p36n5jvdx7bugh2g', // Salon Private
  // 'SalPrivBJ0000008', // Salon Private
  // 'SalPrivBJ0000009', // Salon Private
  // 'SalPrivBJ0000010', // Salon Private
  'sni5cza6d1vvl50i',
  // 'k4r2kvd34eqqb6vh',
  // 'nc3u2l6y0khszjv7',
  'SpeedBlackjack01',
  'SpeedBlackjack02',
  'SpeedBlackjack04',
  'ps3uhj7gteskex37',
  'p2f2uxiym2tmvzgq',
  'p2f25gsom2tmwmpn',
  'qfyyxolocjhfau7y',
  'qfyy4jm6rixfbllh',
  'qfyzapjqrixfb3bx',
  'gkmq0o2hryjyqu30',
  '9f4xhuhdd005xlbl',
  'ehw2fvl831m5n2km',
  'nkyiswhd2jpbw4i4',
  'nkyivihc2jpbw4uy',
  'nsxqkywul2nzcwwh',
  'oa7fpshyqfueqxuj',
  'o7347okwaeasvy2y',
  'o735azzsaeasv2pr',
  'pdk5zo7cey6upxlm',
  'ps3t7j4ykfe2fhdw',
  'ps3t7qv2teskeg4w',
  'p2f2ootrm2tmvk6h',
  'qfyxcoqlrcfe44nj',
  'rctf2h7wbtsmf7rs',
  'pdk54i3vey6up3dg',
  // 'mdkqdxtkdctrhnsx', // Salon Private
  // 'olbinkuoylzayeoj', // Salon Private
  // 'SalPrivBJ0000006', // Salon Private
  // 'uwd2bl2khwcikjlz',
  // 'k4r2ejwx4eqqb6tv',
  // 'xphpcthv8e6ivc16',
  // 'k4r2hyhw4eqqb6us',
  'jhs44mm0v3fi3aux',
  // 'xqyb2u7fqkexxpa0', // Error
  // 'ylq4gmw8yl22u5dj', // Error
  // '1xwfnktjybsolkn6', // Error
  // 'xstnlyzrm345ev95', // Error
  // 'i5j1cyqhrypkih23', // Error
  // 'CFreeBetBjVIP001', // Free bet
  // 'CFreeBetBjVIP003', // Free bet
  // 'CFreeBetBjVIP004', // Free bet
  // 'CFreeBetBjVIP005', // Free bet
  // 'CFreeBetBjVIP006', // Free bet
  // 'CFreeBetBjVIP007', // Free bet
  // 'CFreeBetBjVIP008', // Free bet
  // 'CFreeBetBjVIP009', // Free bet
  // 'CFreeBetBjVIP010', // Free bet
  // 'CFreeBetBjVIP011', // Free bet
  // 'CFreeBetBjVIP012', // Free bet
  // 'CFreeBetBjVIP013', // Free bet
  // 'CFreeBetBjVIP014', // Free bet
  // 'CFreeBetBjVIP015', // Free bet
  // 'CFreeBetBjVIP016', // Free bet
  // 'p5s3fhwum7weobwu', // Error
];

export const ROOM_HAS_NAME = [
  { id: 'Craps00000000001', name: 'クラップス' },
  { id: 'PowerInfiniteBJ1', name: 'パワーブラックジャック' },
  { id: 'mrfykemt5slanyi5', name: 'インフィニット ブラックジャック' },
  { id: 'k4r2hyhw4eqqb6us', name: 'スピードブラックジャック L' },
  { id: 'ESpeedBJ00000002', name: 'Evo スピードブラックジャック 2' },
  { id: 'jhs44mm0v3fi3aux', name: 'ブラックジャック C' },
  { id: 'k4r2kvd34eqqb6vh', name: 'スピード ブラックジャック M' },
  { id: 'ylq4gmw8yl22u5dj', name: 'スピードブラックジャック E' },
  { id: 'nc3u2l6y0khszjv7', name: 'スピードブラックジャック H' },
  { id: 'xstnlyzrm345ev95', name: 'スピードブラックジャック I' },
  { id: 'i5j1cyqhrypkih23', name: 'スピードブラックジャック J' },
  { id: 'SpeedBlackjack04', name: 'スピード VIP ブラックジャック D' },
  { id: 'ps3uhj7gteskex37', name: 'スピード VIP ブラックジャック F' },
  { id: 'ps3uijuskfe2f3cj', name: 'スピード VIP ブラックジャック G' },
  { id: 'p2f2uxiym2tmvzgq', name: 'スピード VIP ブラックジャック H' },
  { id: 'p2f2zs26tc2mu7r5', name: 'スピード VIP ブラックジャック I' },
  { id: 'p2f25gsom2tmwmpn', name: 'スピード VIP ブラックジャック J' },
  { id: 'qfyyxolocjhfau7y', name: 'スピード VIP ブラックジャック K' },
  { id: 'qfyy4jm6rixfbllh', name: 'スピード VIP ブラックジャック L' },
  { id: 'SpeedBlackjack14', name: 'スピード VIP ブラックジャック N' },
  { id: 'SpeedBlackjack15', name: 'スピード VIP ブラックジャック O' },
  { id: 'SpeedBlackjack16', name: 'スピード VIP ブラックジャック P' },
  { id: 'SpeedBlackjack17', name: 'スピード VIP ブラックジャック Q' },
  { id: 'SpeedBlackjack18', name: 'スピード VIP ブラックジャック R' },
  { id: 'CFreeBetBjVIP002', name: 'フリーベットの VIP ブラックジャック B' },
  { id: 'CFreeBetBjVIP003', name: 'フリーベットの VIP ブラックジャック A' },
  { id: '9f4xhuhdd005xlbl', name: 'ブラックジャック銀 B' },
  { id: 'ehw2fvl831m5n2km', name: 'ブラックジャック VIP F' },
  { id: 'nkyiswhd2jpbw4i4', name: 'ブラックジャック VIP N' },
  { id: 'nkyivihc2jpbw4uy', name: 'ブラックジャック VIP O' },
  { id: 'nsxqkywul2nzcwwh', name: 'ブラックジャック VIP P' },
  { id: 'nveq66tfmn6n4moi', name: 'ブラックジャック VIP T' },
  { id: 'bciewncrf5ijneys', name: 'ブラックジャック VIP U' },
  { id: '2uxabtm1rwaxcmdm', name: 'ブラックジャック VIP V' },
  { id: 'o735di2eiwssv7eu', name: 'ブラックジャック VIP 4' },
  { id: 'o735efxfaeasv666', name: 'ブラックジャック VIP 5' },
  { id: 'o735fhvsaeaswamh', name: 'ブラックジャック VIP 6' },
  { id: 'pdk5xfrkjkgepmlq', name: 'ブラックジャック VIP 9' },
  { id: 'pdk5yexcz4iepelq', name: 'ブラックジャック VIP 10' },
  { id: 'pdk5yzyfjkgepoml', name: 'ブラックジャック VIP 11' },
  { id: 'pdk5zo7cey6upxlm', name: 'ブラックジャック VIP 12' },
  { id: 'pdk52e3rey6upyie', name: 'ブラックジャック VIP 13' },
  { id: 'pdk523jney6upzft', name: 'ブラックジャック VIP 14' },
  { id: 'ps3t7j4ykfe2fhdw', name: 'ブラックジャック VIP 17' },
  { id: 'ps3t7nhskfe2fhkj', name: 'ブラックジャック VIP 18' },
  { id: 'ps3t7qv2teskeg4w', name: 'ブラックジャック VIP 19' },
  { id: 'p2fzwauitc2msrik', name: 'ブラックジャック VIP 20' },
  { id: 'p2f2lphftc2muaql', name: 'ブラックジャック VIP 21' },
  { id: 'p2f2ootrm2tmvk6h', name: 'ブラックジャック VIP 22' },
  { id: 'qfyw6u63rixe3foz', name: 'ブラックジャック VIP 25' },
  { id: 'qfyxcoqlrcfe44nj', name: 'ブラックジャック VIP 26' },
  { id: 'qfyxgwwsrcfe5lq3', name: 'ブラックジャック VIP 27' },
  { id: 'q6wo6fjprnlhuf36', name: 'ブラックジャック VIP 28' },
  { id: 'q6wo7mqrrnlhuj6b', name: 'ブラックジャック VIP 29' },
  { id: 'rctfyut2btsmfyyt', name: 'ブラックジャック VIP 30' },
  { id: 'rctf2h7wbtsmf7rs', name: 'ブラックジャック VIP 31' },
  { id: 'rctf4gu6btsmghbt', name: 'ブラックジャック VIP 32' },
  { id: 'oqicznoauwbl46am', name: 'ブラックジャック VIP アルファ' },
  { id: 'oqic5sqbt25322zm', name: 'ブラックジャック VIP ベータ' },
  { id: 'oqidcfpsuwbl5cqd', name: 'ブラックジャック VIP ガンマ' },
  { id: 'qlrc3fq3v7p6awm4', name: 'ブラックジャック銀 C' },
  { id: 'qckwjf2o52r9ikeb', name: 'ブラックジャック銀 D' },
  { id: 'gazgtkid9h1b0dn9', name: 'ブラックジャック銀 E' },
  { id: 'cpxl81x0rgi34cmo', name: 'ブラックジャック VIP B' },
  { id: 'psm2um7k4da8zwc2', name: 'ブラックジャック VIP E' },
  { id: 'm6mfo66sb7eafnzz', name: 'ブラックジャック VIP J' },
  { id: 'm6mfsirtb7eafn5c', name: 'ブラックジャック VIP K' },
  { id: 'nbjettfehawanhes', name: 'ブラックジャック VIP L' },
  { id: 'oa7fvyaiqfueq5ob', name: 'ブラックジャック VIP Q' },
  { id: 'bghflgi59db7d7r2', name: 'ブラックジャック VIP X' },
  { id: 'o735ggd5iwsswcz7', name: 'ブラックジャック VIP 7' },
  { id: 'o735hfcqauecwjxp', name: 'ブラックジャック VIP 8' },
  { id: 'pdk53n4bjkgepr5u', name: 'ブラックジャック VIP 15' },
  { id: 'pdk54i3vey6up3dg', name: 'ブラックジャック VIP 16' },
  { id: 'lnofoyxv756qaezy', name: 'ブラックジャック銀 F' },
  { id: 'lnofpmm3756qae2c', name: 'ブラックジャック銀 G' },
  { id: 'l5aug44hhzr3qvxs', name: 'ブラックジャック VIP C' },
  { id: 'z5pf5pichcsw3d2o', name: 'ブラックジャック VIP G' },
  { id: 's63nx2mpdomgjagb', name: 'ブラックジャック VIP H' },
  { id: 'lnofn2yl756qaezm', name: 'ブラックジャック VIP I' },
  { id: 'h463tlq1rhl1lfr2', name: 'ブラックジャック プラチナ VIP' },
  { id: 'ejx1a04w4ben0mou', name: 'ブラックジャック フォーチュン VIP' },
  { id: 'nbjetztthawanhey', name: 'ブラックジャック VIP M' },
  { id: 'nsxqpyiol2nzcz6t', name: 'ブラックジャック VIP R' },
  { id: 'rdefcn4sffgo39l7', name: 'ブラックジャック ダイヤモンド VIP' },
  { id: 'olbibp3fylzaxvhb', name: 'サロンプリヴェ ブラックジャック B' },
  { id: 'mdkqfe74dctrhntj', name: 'サロンプリヴェ ブラックジャック C' },
  { id: 'SalPrivBJ0000005', name: 'サロンプリヴェ ブラックジャック E' },
  { id: 'p36n5jvdx7bugh2g', name: 'サロンプリヴェ ブラックジャック G' },
  { id: 'SalPrivBJ0000009', name: 'サロンプリヴェ ブラックジャック I' },
  { id: 'olbinkuoylzayeoj', name: 'サロンプリヴェ ブラックジャック D' },
  { id: 'SalPrivBJ0000006', name: 'サロンプリヴェ ブラックジャック F' },
  { id: 'sni5cza6d1vvl50i', name: 'ブラックジャック パーティ' },
  { id: 'uwd2bl2khwcikjlz', name: 'ブラックジャック A' },
  { id: 'k4r2ejwx4eqqb6tv', name: 'スピードブラックジャック K' },
  { id: 'xphpcthv8e6ivc16', name: 'ブラックジャック B' },
  { id: 'ESpeedBJ00000001', name: 'Evo スピードブラックジャック 1' },
  { id: 'ESpeedBJ00000003', name: 'Evo スピードブラックジャック 3' },
  { id: 'xqyb2u7fqkexxpa0', name: 'スピードブラックジャック D' },
  { id: '1xwfnktjybsolkn6', name: 'スピードブラックジャック G' },
  { id: 'SpeedBlackjack01', name: 'スピード VIP ブラックジャック A' },
  { id: 'SpeedBlackjack02', name: 'スピード VIP ブラックジャック B' },
  { id: 'SpeedBlackjack03', name: 'スピード VIP ブラックジャック C' },
  { id: 'ps3ufteekfe2fu24', name: 'スピード VIP ブラックジャック E' },
  { id: 'qfyzapjqrixfb3bx', name: 'スピード VIP ブラックジャック M' },
  { id: 'gkmq0o2hryjyqu30', name: 'ブラックジャック銀 A' },
  { id: 'nveq65dtmn6n4mnd', name: 'ブラックジャック VIP S' },
  { id: 'oa7fpshyqfueqxuj', name: 'ブラックジャック VIP Z' },
  { id: 'o7347okwaeasvy2y', name: 'ブラックジャック VIP 1' },
  { id: 'o735azzsaeasv2pr', name: 'ブラックジャック VIP 2' },
  { id: 'o735cjzyaeasv4o6', name: 'ブラックジャック VIP 3' },
  { id: '0mvn914lkmo9vaq8', name: 'ブラックジャック VIP A' },
  { id: 'o3d9tx3u8kd0yawc', name: 'ブラックジャック VIP D' },
  { id: 'gfzrqe4hqv24kukc', name: 'ブラックジャック グランド VIP' },
  { id: 'mdkqdxtkdctrhnsx', name: 'サロンプリヴェ ブラックジャック A' },
  { id: 'SalPrivBJ0000008', name: 'サロンプリヴェ ブラックジャック H' },
  { id: 'SalPrivBJ0000010', name: 'サロンプリヴェ ブラックジャック J' },
];
